### ISSUE TITLE
Slow and laggy response in `cht`

### ISSUE THREAD

**Issue by naxl** [jopemachine/alfred-chromium-workflow#13]
I don't know what I did wrong, but the response time for the search tab is very slow, and it lags and not respond for few seconds, please find a fix to it soon.

**Comment by jopemachine** [comment]
Could you let me know your mac's hardware specification?
Is this also happen when you use 0.2.7?

**Comment by naxl** [comment]
Specs-

Core i5-1035G7
MBP 2020 16 gigs and 512 ssd.

I think I found a workaround, so creating a fresh new user fixes it temp. but its not a solid fix. I am using latest release.

**Comment by jopemachine** [comment]
0.2.7 version is the last version that I built this workflow with an intel mac, I changed a compiler flag on the latest version to build the workflow with m1 mac, and I think it might be related because I didn't receive the `cht` slow issue until that build.

But I cannot test it because I don't have intel mac now, so could you test if this slow response is reproducible on 0.2.7?

If the slow response is not reproducible on 0.2.7, I think it must be related.

**Comment by naxl** [comment]
It is not reproducible. I tried, its once in a while type of bug. Idk. By the way, keep it up, great work! :)
